# Generated by Django 5.0.7 on 2025-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lang",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lat",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
