# Generated by Django 5.0.7 on 2025-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_customuser_lang_customuser_lat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
